### ISSUE TITLE
配网问题

### ISSUE THREAD

**Issue by RedSun001** [TuyaInc/tuyasmart_home_android_sdk#10]
配网EZ模式报错：
Process: com.boe.home, PID: 27804
    java.lang.UnsatisfiedLinkError: No implementation found for void com.tuya.smart.android.device.TuyaSmartLink.sendStatusStop() (tried Java_com_tuya_smart_android_device_TuyaSmartLink_sendStatusStop and Java_com_tuya_smart_android_device_TuyaSmartLink_sendStatusStop__)
        at com.tuya.smart.android.device.TuyaSmartLink.sendStatusStop(Native Method)
        at com.tuya.smart.common.rs.a(TuyaEZConfig.java:40)
        at com.tuya.smart.common.jn.a(TuyaEZConfigImpl.java:16)
        at com.tuya.smart.common.du.c(MultiEZSearchNew.java:168)
        at com.tuya.smart.common.du.a(MultiEZSearchNew.java:185)
        at com.tuya.smart.common.du.a(MultiEZSearchNew.java:176)
        at com.tuya.smart.common.du.a(MultiEZSearchNew.java:151)
        at com.tuya.smart.common.ds.start(MultiEZConfig.java:215)
        at com.tuya.smart.common.ef.c(TuyaMultiEasyConnect.java:31)
        at com.tuya.smart.common.ef.start(TuyaMultiEasyConnect.java:49)
        at com.tuya.smart.common.ee.start(TuyaMultiConnect.java:124)
        at com.boe.home.MainActivity1.startPeiwang(MainActivity1.java:192)
        at com.boe.home.MainActivity1.access$500(MainActivity1.java:31)
        at com.boe.home.MainActivity1$6.onSuccess(MainActivity1.java:162)
        at com.tuya.smart.common.dw$1.b(TuyaActivator.java:86)
        at com.tuya.smart.common.dw$1.onSuccess(TuyaActivator.java:75)
        at com.tuya.smart.android.network.Business$RequestTask$3.run(Business.java:447)
        at android.os.Handler.handleCallback(Handler.java:808)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7529)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by woodknife2019** [comment]
设备配网这一关一直过不去

**Comment by woodknife2019** [comment]
我们配网用的手机做热点，请问这个会影响配网吗？

**Comment by hackill** [comment]
手机的热点可以的。需要2.4G频段

**Comment by woodknife2019** [comment]
我们按照demo跑了一下，还是一跑就崩，错误代码如上

**Comment by hackill** [comment]
手机是什么型号

**Comment by woodknife2019** [comment]
华为p10 plus

**Comment by hackill** [comment]
怀疑是你那边或者初始化什么的没做完。 不是按照demo跑一下，是跑一下demo哦。我刚跑了demo ，是正常配网和其他操作。你那边先试一下demo吧 记得再manifest中替换你们申请的key和secret。 demo几分钟就可以跑起来了

**Comment by hackill** [comment]
我刚跑的demo apk文件你可以再你那边的手机上装一下。  记得账号需要重新申请，因为appkey换了。
https://fir.im/h7su

**Comment by woodknife2019** [comment]
我们跑了一下你们的demo，可以正常配网和其他操作，但是换成我们的代码（目检和demo的一样）就会出现崩的状况，代码错误如上。很奇怪，正在排查

**Comment by hackill** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    注意看下 application中的初始化
