### ISSUE TITLE
Release apk crashed Android tuya 

### ISSUE THREAD

**Issue by tkhabbab** [TuyaInc/tuyasmart_home_android_sdk#218]
I have faced a problem when I run my app in debug mode it's work fine but when i build a release apk it crashed.

`Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
at com.tuya.smart.android.base.provider.ApiUrlProvider.getPhoneCode(ApiUrlProvider.java:183)
at com.tuya.smart.android.base.provider.ApiUrlProvider.getDefaultRegion(ApiUrlProvider.java:163)
at com.tuya.smart.android.base.provider.ApiUrlProvider.getDefaultRegion(ApiUrlProvider.java:106)
at com.tuya.smart.android.base.provider.ApiUrlProvider.<init>(ApiUrlProvider.java:93)
at com.tuya.smart.sdk.TuyaSdk.initTuyaData(TuyaSdk.java:72)
at com.tuya.smart.sdk.TuyaSdk.init(TuyaSdk.java:146)
at com.tuya.smart.sdk.TuyaSdk.init(TuyaSdk.java:57)
at com.tuya.smart.home.sdk.TuyaHomeSdk.init(TuyaHomeSdk.java:97)`

**Comment by T-Caster** [comment]
did you solve this problem?
I'm having the same problem too
