### ISSUE TITLE
panelcontroller issue

### ISSUE THREAD

**Issue by rndtester** [TuyaInc/tuyasmart_home_android_sdk#32]
Hi, I'm having error on the panelcontroller issue at the smart socket. When i press any on the list(sample switch 1, switch 2 switch 3.....), it crashes.

this is the line of code was pointing at

protected void initToolbar() {
        if (this.mToolBar == null) {
            this.mToolBar = (Toolbar)this.findViewById(id.toolbar_top_view);
            if (this.mToolBar != null) {
                this.setToolBarColor(-13619152);
            }
        }

and this is the error

java.lang.NoSuchFieldError: No static field toolbar_top_view of type I in class Lcom/tuya/smart/R$id; or its superclasses (declaration of 'com.tuya.smart.R$id' appears in /data/app/com.cherry.home-2/base.apk:classes2.dex)
        at com.tuya.sdk.panel.base.activity.ToolbarActivity.initToolbar(ToolbarActivity.java:19)
        at com.tuya.sdk.panel.alarm.activity.AlarmActivity.onCreate(AlarmActivity.java:70)
        at com.tuya.sdk.panel.alarm.activity.NewDpAlarmActivity.onCreate(NewDpAlarmActivity.java:14)
        at android.app.Activity.performCreate(Activity.java:6877)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3208)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3351)
        at android.app.ActivityThread.access$1100(ActivityThread.java:222)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1796)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:158)
        at android.app.ActivityThread.main(ActivityThread.java:7230)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by yueshituya** [comment]
What pane SDK version you used? What is your socket PID?

**Comment by rndtester** [comment]
What pane SDK version you used?
- 0.0.3
 What is your socket PID?
- k0rPvM4kSzFeifWG

**Comment by yueshituya** [comment]
Please update panel SDK to 0.0.7 or 0.0.8. Clean your project and rebuild.

**Comment by rndtester** [comment]
can you give me the panel SDK 0.0.8

**Comment by yueshituya** [comment]
Panel SDK repo is [here](https://gitlab.com/TuyaSmartPanel/tuyasmart_panel_android_sdk), AAR is [here](https://gitlab.com/TuyaSmartPanel/tuyasmart_panel_android_sdk/blob/master/libs/tuyapanel-0.0.8.aar). You can check out version you need.

**Comment by rndtester** [comment]
already added the 0.0.8 then clean then rebuild
but still getting the same error. please help. asap. thx

**Comment by NextApp** [comment]
@rndtester  is error solved ?
