### ISSUE TITLE
Getting this issue on add device

### ISSUE THREAD

**Issue by 4naveen** [TuyaInc/tuyasmart_home_android_sdk#49]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.test.homesdkdemo/com.tuya.smart.android.demo.config.ECBindActivity}: java.lang.StringIndexOutOfBoundsException: length=8; regionStart=2; regionLength=8
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2505)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2577)
        at android.app.ActivityThread.access$1000(ActivityThread.java:164)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1462)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:160)
        at android.app.ActivityThread.main(ActivityThread.java:5541)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
     Caused by: java.lang.StringIndexOutOfBoundsException: length=8; regionStart=2; regionLength=8
        at java.lang.String.startEndAndLength(String.java:504)
        at java.lang.String.substring(String.java:1333)
        at com.tuya.smart.interior.config.bean.ActiveTokenBean.<init>(ActiveTokenBean.java:15)
        at com.tuya.smart.common.cu.a(MultiEZSearchNew.java:151)
        at com.tuya.smart.common.cs.start(MultiEZConfig.java:215)
        at com.tuya.smart.common.de.c(TuyaMultiEasyConnect.java:31)
        at com.tuya.smart.common.de.start(TuyaMultiEasyConnect.java:49)
        at com.tuya.smart.common.dd.start(TuyaMultiConnect.java:124)
        at com.tuya.smart.android.demo.config.DeviceBindModel.start(DeviceBindModel.java:50)
        at com.tuya.smart.android.demo.config.ECBindPresenter.startSearch(ECBindPresenter.java:103)
        at com.tuya.smart.android.demo.config.ECBindPresenter.initConfigDevice(ECBindPresenter.java:96)
        at com.tuya.smart.android.demo.config.ECBindPresenter.<init>(ECBindPresenter.java:57)
        at com.tuya.smart.android.demo.config.ECBindActivity.initPresenter(ECBindActivity.java:180)
        at com.tuya.smart.android.demo.config.ECBindActivity.onCreate(ECBindActivity.java:64)
        at android.app.Activity.performCreate(Activity.java:6093)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2458)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2577) 
        at android.app.ActivityThread.access$1000(ActivityThread.java:164) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1462) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:160) 
        at android.app.ActivityThread.main(ActivityThread.java:5541) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)

**Comment by NextApp** [comment]
the data of token is error, pls confirm it .

**Comment by 4naveen** [comment]
> the data of token is error, pls confirm it .

I am using token generated based on uid

**Comment by 4naveen** [comment]
> the data of token is error, pls confirm it .

can you please tell how i can be sure that token which genereted based on uid is valid
