### ISSUE TITLE
Device addition issue based on uid 

### ISSUE THREAD

**Issue by 4naveen** [TuyaInc/tuyasmart_home_android_sdk#51]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.test.homesdkdemo/com.tuya.smart.android.demo.config.ECBindActivity}: java.lang.StringIndexOutOfBoundsException: length=8; regionStart=2; regionLength=8
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2505)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2577)
        at android.app.ActivityThread.access$1000(ActivityThread.java:164)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1462)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:160)
        at android.app.ActivityThread.main(ActivityThread.java:5541)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)

**Comment by NextApp** [comment]
cloud you pls show the token?

**Comment by 4naveen** [comment]
> java.lang.RuntimeException: Unable to start activity ComponentInfo{com.test.homesdkdemo/com.tuya.smart.android.demo.config.ECBindActivity}: java.lang.StringIndexOutOfBoundsException: length=8; regionStart=2; regionLength=8
> at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2505)
> at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2577)
> at android.app.ActivityThread.access$1000(ActivityThread.java:164)
> at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1462)
> at android.os.Handler.dispatchMessage(Handler.java:102)
> at android.os.Looper.loop(Looper.java:160)
> at android.app.ActivityThread.main(ActivityThread.java:5541)
> at java.lang.reflect.Method.invoke(Native Method)
> at java.lang.reflect.Method.invoke(Method.java:372)
> at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)

I have ge

> cloud you pls show the token?

Sure

Token-rfqDEJQR
Uid-ay1560760639676vueAy
Pwd--test1

**Comment by NextApp** [comment]
the token is error ,how do you get it ?
