### ISSUE TITLE
TutkMoniterHardVideoView not get intialized

### ISSUE THREAD

**Issue by 4naveen** [TuyaInc/tuyasmart_home_android_sdk#6]
The following classes could not be instantiated:
- com.tuya.tutk.view.TutkMoniterHardVideoView (Open Class, Show Exception, Clear Cache)
 Tip: Use View.isInEditMode() in your custom views to skip code or show sample data when shown in the IDE.

**Comment by TuyaRockSugar** [comment]
use the branch release/v3.0.0
https://gitlab.com/TuyaSmartCamera/tuyasmart_camera_android_sdk/tree/release/v3.0.0 

<com.tuya.smart.camera.middleware.view.TuyaMonitorView
            android:id="@+id/camera_video_view"
            android:layout_width="match_parent"
            android:layout_height="wrap_content" />

**Comment by 4naveen** [comment]
I am trying to build this sample in my ide but it is not getting build 
error

Could not GET 'http://maven.aliyun.com/nexus/content/groups/public/xerces/xercesImpl/2.9.1/xercesImpl-2.9.1.jar'. Received status code 500 from server: Operation not permitted
Enable Gradle 'offline mode' and sync project

**Comment by 4naveen** [comment]
Caused by: org.gradle.internal.resolve.ArtifactResolveException: Could not download xercesImpl.jar (xerces:xercesImpl:2.9.1)
	at org.gradle.api.internal.artifacts.repositories.resolver.ExternalResourceResolver$RemoteRepositoryAccess.resolveArtifact(ExternalResourceResolver.java:506)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository$ResolveAndCacheRepositoryAccess.resolveArtifact(CachingModuleComponentRepository.java:409)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.BaseModuleComponentRepositoryAccess.resolveArtifact(BaseModuleComponentRepositoryAccess.java:65)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.memcache.InMemoryCachedModuleComponentRepository$CachedAccess.resolveArtifact(InMemoryCachedModuleComponentRepository.java:124)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.ErrorHandlingModuleComponentRepository$ErrorHandlingModuleComponentRepositoryAccess.resolveArtifact(ErrorHandlingModuleComponentRepository.java:171)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainArtifactResolver.resolveArtifact(RepositoryChainArtifactResolver.java:80)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.artifact.DefaultArtifactSet$LazyArtifactSource.create(DefaultArtifactSet.java:171)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.artifact.DefaultArtifactSet$LazyArtifactSource.create(DefaultArtifactSet.java:158)
	at org.gradle.api.internal.artifacts.DefaultResolvedArtifact.getFile(DefaultResolvedArtifact.java:135)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.artifact.ArtifactBackedResolvedVariant$DownloadArtifactFile.run(ArtifactBackedResolvedVariant.java:146)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.access$900(DefaultBuildOperationExecutor.java:63)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$ParentPreservingQueueWorker.execute(DefaultBuildOperationExecutor.java:378)
	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.runOperation(DefaultBuildOperationQueue.java:230)
	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.access$600(DefaultBuildOperationQueue.java:172)
	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable$1.call(DefaultBuildOperationQueue.java:209)
	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable$1.call(DefaultBuildOperationQueue.java:203)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:152)
	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.runBatch(DefaultBuildOperationQueue.java:202)
	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.run(DefaultBuildOperationQueue.java:177)
	... 6 more
Caused by: org.gradle.api.resources.ResourceException: Could not get resource 'http://maven.aliyun.com/nexus/content/groups/public/xerces/xercesImpl/2.9.1/xercesImpl-2.9.1.jar'.
	at org.gradle.internal.resource.ResourceExceptions.failure(ResourceExceptions.java:74)
	at org.gradle.internal.resource.ResourceExceptions.getFailed(ResourceExceptions.java:57)
	at org.gradle.internal.resource.transfer.DefaultCacheAwareExternalResourceAccessor.copyToCache(DefaultCacheAwareExternalResourceAccessor.java:201)
	at org.gradle.internal.resource.transfer.DefaultCacheAwareExternalResourceAccessor.access$300(DefaultCacheAwareExternalResourceAccessor.java:55)
	at org.gradle.internal.resource.transfer.DefaultCacheAwareExternalResourceAccessor$1.create(DefaultCacheAwareExternalResourceAccessor.java:155)
	at org.gradle.internal.resource.transfer.DefaultCacheAwareExternalResourceAccessor$1.create(DefaultCacheAwareExternalResourceAccessor.java:82)
	at org.gradle.cache.internal.ProducerGuard$AdaptiveProducerGuard.guardByKey(ProducerGuard.java:97)
	at org.gradle.internal.resource.transfer.DefaultCacheAwareExternalResourceAccessor.getResource(DefaultCacheAwareExternalResourceAccessor.java:82)
	at org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver.downloadByCoords(DefaultExternalResourceArtifactResolver.java:129)
	at org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver.downloadStaticResource(DefaultExternalResourceArtifactResolver.java:95)
	at org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver.resolveArtifact(DefaultExternalResourceArtifactResolver.java:67)
	at org.gradle.api.internal.artifacts.repositories.resolver.ExternalResourceResolver$RemoteRepositoryAccess.resolveArtifact(ExternalResourceResolver.java:499)
	... 27 more
Caused by: org.gradle.internal.resource.transport.http.HttpErrorStatusCodeException: Could not GET 'http://maven.aliyun.com/nexus/content/groups/public/xerces/xercesImpl/2.9.1/xercesImpl-2.9.1.jar'. Received status code 500 from server: Operation not permitted
	at org.gradle.internal.resource.transport.http.HttpClientHelper.processResponse(HttpClientHelper.java:158)
	at org.gradle.internal.resource.transport.http.HttpClientHelper.performGet(HttpClientHelper.java:84)
	at org.gradle.internal.resource.transport.http.HttpResourceAccessor.openResource(HttpResourceAccessor.java:43)
	at org.gradle.internal.resource.transport.http.HttpResourceAccessor.openResource(HttpResourceAccessor.java:29)
	at org.gradle.internal.resource.transfer.DefaultExternalResourceConnector.openResource(DefaultExternalResourceConnector.java:56)
	at org.gradle.internal.resource.transfer.ProgressLoggingExternalResourceAccessor.openResource(ProgressLoggingExternalResourceAccessor.java:36)
	at org.gradle.internal.resource.transfer.AccessorBackedExternalResource.withContentIfPresent(AccessorBackedExternalResource.java:130)
	at org.gradle.internal.resource.BuildOperationFiringExternalResourceDecorator$11.call(BuildOperationFiringExternalResourceDecorator.java:237)
	at org.gradle.internal.resource.BuildOperationFiringExternalResourceDecorator$11.call(BuildOperationFiringExternalResourceDecorator.java:229)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:350)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:340)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:120)
	at org.gradle.internal.resource.BuildOperationFiringExternalResourceDecorator.withContentIfPresent(BuildOperationFiringExternalResourceDecorator.java:229)
	at org.gradle.internal.resource.transfer.DefaultCacheAwareExternalResourceAccessor.copyToCache(DefaultCacheAwareExternalResourceAccessor.java:199)
	... 36 more

**Comment by TuyaRockSugar** [comment]
delete the code in  build.gradle
maven{ url 'http://maven.aliyun.com/nexus/content/groups/public'}

**Comment by 4naveen** [comment]
I am intregating sample code you given with TuyaSmartHomeSdkDemo Example 
but error is coming at build time
  Program type already present: com.tutk.IOTC.APPInfo
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.

can you please give some solution asap

**Comment by 4naveen** [comment]
apply plugin: 'com.android.application'

android {
    compileSdkVersion 28
    buildToolsVersion "28.0.3"
    defaultConfig {
        applicationId "com.test.homesdkdemo"
        minSdkVersion 16
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
        Properties properties = new Properties()
        properties.load(project.rootProject.file('local.properties').newDataInputStream())
        manifestPlaceholders = [TUYA_SMART_APPKEY: "${properties.getProperty("appkey")}", TUYA_SMART_SECRET: "${properties.getProperty("appsecret")}"]
    }
    buildTypes {
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }
    repositories {
        flatDir {
            dirs 'libs' //this way we can find the .aar file in libs folder
        }
    }

    lintOptions {
        abortOnError false
        disable 'InvalidPackage'
    }

}

dependencies {
    implementation fileTree(include: ['*.jar', '*.aar'], dir: 'libs')
    //***** required ****//
    implementation 'com.alibaba:fastjson:1.1.67.android'
    implementation 'com.squareup.okhttp3:okhttp-urlconnection:3.6.0'
    implementation 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.0'
    implementation(name: 'tuyaCamera-3.0.2', ext: 'aar')
    implementation(name: 'tuyasmart-2.7.5', ext: 'aar')
//***** required ****//
    // implementation(name: 'tutkcamerasdk-release', ext: 'aar')
    //implementation(name: 'IOTCamera_2.4.1_release', ext: 'aar')
    //  implementation(name: 'libLocalRecorder-2.0.4', ext: 'aar')
    //  implementation(name: 'libMediaConvert-2.0.4', ext: 'aar')
    //implementation(name: 'libSLC-1.0.8', ext: 'aar')
    // implementation(name: 'avioctrldefine-v3_1_5_20-release', ext: 'aar')

    //***** not required ****//
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    implementation 'org.greenrobot:eventbus:3.0.0'
    implementation 'com.wnafee:vector-compat:1.0.5'
    implementation 'com.jakewharton:butterknife:8.8.1'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.8.1'
    implementation 'com.kyleduo.switchbutton:library:1.4.2'
    implementation 'com.android.support:recyclerview-v7:28.0.0'
    implementation 'com.squareup.picasso:picasso:2.5.2'
    implementation 'com.readystatesoftware.systembartint:systembartint:1.0.3'
    //***** not required ****//
    implementation 'com.google.code.gson:gson:2.2.4'
}

**Comment by 4naveen** [comment]
this is my app level gradle

**Comment by 4naveen** [comment]
tried already but it is not working

**Comment by 4naveen** [comment]
I tried invalidate cache and restart now i am getting this error

* What went wrong:
Execution failed for task ':app:transformNativeLibsWithMergeJniLibsForDebug'.
> More than one file was found with OS independent path 'lib/armeabi-v7a/libAVAPIs.so'

**Comment by 4naveen** [comment]
yes ,somehow I fixed that issue now at runtime i am getting 

01-25 15:20:09.485 8242-8242/com.test.homesdkdemo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.test.homesdkdemo, PID: 8242
    java.lang.NoClassDefFoundError: com.tuya.smart.common.jw$1$3
        at com.tuya.smart.common.jw$1.b(HomeListBusiness.java:144)
        at com.tuya.smart.common.jw$1.onSuccess(HomeListBusiness.java:134)
        at com.tuya.smart.android.network.Business$RequestTask$3.run(Business.java:446)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:160)
        at android.app.ActivityThread.main(ActivityThread.java:5541)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)

**Comment by 4naveen** [comment]
ok

**Comment by 4naveen** [comment]
![screenshot 48](https://user-images.githubusercontent.com/24203901/51740665-a8d44400-20ba-11e9-983d-ac71fb6cc98f.png)

**Comment by TuyaRockSugar** [comment]
![image](https://user-images.githubusercontent.com/46557951/51741984-5f442300-20d3-11e9-9fb7-5d0a89ee0d9f.png)
import again

**Comment by 4naveen** [comment]
This thing i have corrected already done that's why project got build successfully but at runtime it crashing with this issue

01-25 15:20:09.485 8242-8242/com.test.homesdkdemo E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.test.homesdkdemo, PID: 8242
java.lang.NoClassDefFoundError: com.tuya.smart.common.jw$1$3
at com.tuya.smart.common.jw$1.b(HomeListBusiness.java:144)
at com.tuya.smart.common.jw$1.onSuccess(HomeListBusiness.java:134)
at com.tuya.smart.android.network.Business$RequestTask$3.run(Business.java:446)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:160)
at android.app.ActivityThread.main(ActivityThread.java:5541)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)

**Comment by 4naveen** [comment]
java.lang.NoClassDefFoundError: com.tuya.smart.common.jw$1$3

I succussfully build all libs but why i m getting noclassfound error

**Comment by 4naveen** [comment]
Latest build.gradle

apply plugin: 'com.android.application'

android {
    compileSdkVersion 28
    buildToolsVersion "28.0.3"
    defaultConfig {
        applicationId "com.test.homesdkdemo"
        minSdkVersion 16
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
        Properties properties = new Properties()
        properties.load(project.rootProject.file('local.properties').newDataInputStream())
        manifestPlaceholders = [TUYA_SMART_APPKEY: "${properties.getProperty("appkey")}", TUYA_SMART_SECRET: "${properties.getProperty("appsecret")}"]
    }
    dexOptions {
        preDexLibraries = false
    }
    buildTypes {
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }
    repositories {
        flatDir {
            dirs 'libs' //this way we can find the .aar file in libs folder
        }
    }

    lintOptions {
        abortOnError false
        disable 'InvalidPackage'
    }
    packagingOptions {
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/INDEX.LIST'
        exclude 'META-INF/services/javax.annotation.processing.Processor'
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    //***** required ****//
    implementation 'com.alibaba:fastjson:1.1.67.android'
    implementation 'com.squareup.okhttp3:okhttp-urlconnection:3.6.0'
    implementation 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.0'
    implementation(name: 'tuyaCamera-3.0.2', ext: 'aar')
    implementation(name: 'tuyasmart-2.7.5', ext: 'aar')
//***** required ****//
    // implementation(name: 'tutkcamerasdk-release', ext: 'aar')
    //implementation(name: 'IOTCamera_2.4.1_release', ext: 'aar')
    //  implementation(name: 'libLocalRecorder-2.0.4', ext: 'aar')
    //  implementation(name: 'libMediaConvert-2.0.4', ext: 'aar')
    //implementation(name: 'libSLC-1.0.8', ext: 'aar')
    // implementation(name: 'avioctrldefine-v3_1_5_20-release', ext: 'aar')

    //***** not required ****//
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    implementation 'org.greenrobot:eventbus:3.0.0'
    implementation 'com.wnafee:vector-compat:1.0.5'
    implementation 'com.jakewharton:butterknife:8.8.1'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.8.1'
    implementation 'com.kyleduo.switchbutton:library:1.4.2'
    implementation 'com.android.support:recyclerview-v7:28.0.0'
    implementation 'com.squareup.picasso:picasso:2.5.2'
    implementation 'com.readystatesoftware.systembartint:systembartint:1.0.3'
    //***** not required ****//
    implementation 'com.google.code.gson:gson:2.2.4'
}

**Comment by Tuya-DJ** [comment]
> yes ,somehow I fixed that issue now at runtime i am getting
> 
> 01-25 15:20:09.485 8242-8242/com.test.homesdkdemo E/AndroidRuntime: FATAL EXCEPTION: main
> Process: com.test.homesdkdemo, PID: 8242
> java.lang.NoClassDefFoundError: com.tuya.smart.common.jw$1$3
> at com.tuya.smart.common.jw$1.b(HomeListBusiness.java:144)
> at com.tuya.smart.common.jw$1.onSuccess(HomeListBusiness.java:134)
> at com.tuya.smart.android.network.Business$RequestTask$3.run(Business.java:446)
> at android.os.Handler.handleCallback(Handler.java:739)
> at android.os.Handler.dispatchMessage(Handler.java:95)
> at android.os.Looper.loop(Looper.java:160)
> at android.app.ActivityThread.main(ActivityThread.java:5541)
> at java.lang.reflect.Method.invoke(Native Method)
> at java.lang.reflect.Method.invoke(Method.java:372)
> at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)

please add proguard-rules.pro: https://tuyainc.github.io/tuyasmart_home_android_sdk_doc/en/resource/Integrated.html

**Comment by 4naveen** [comment]
Hi , I am getting issue when i try to connect with device from app i.e..  when i calling camera.connect(..)
error--
onChannelOtherStatus errorCode -4

 @Override
    public void onChannelOtherStatus(int errorCode) {
        Log.e(TAG, "onChannelOtherStatus errorCode " + errorCode);
    }

**Comment by 4naveen** [comment]
one more doubt is how i will get these two value
  mInitStr , mP2pKey

**Comment by Tuya-DJ** [comment]
https://tuyainc.github.io/tuyasmart_camera_android_sdk_doc/en/resource/parameters.html

**Comment by Tuya-DJ** [comment]
please, show me your devId and the response of requestWithApiName()

**Comment by 4naveen** [comment]
E/response: {"audioAttributes":{"callMode":[1,2],"hardwareCapability":[1,2]},"id":"6c6ad23b242b9be9e7umcb","p2pConfig":{},"p2pId":"6EWMNNSSA67V2SET111A","password":"ad517d71","skill":"{\"chromecast\":1,\"localStorage\":1,\"sdk_version\":\"3.4.2\",\"echoshow\":1,\"cloudStorage\":1}","timeZoneId":"Asia/Calcutta"}

**Comment by 4naveen** [comment]
I am getting this response for doorbell 
 E/response: {"audioAttributes":{"callMode":[1,2],"hardwareCapability":[1,2]},"id":"6c17869d9c18886d29tze0","p2pConfig":{"crcKey":"vlkE30ib","initStr":"EEGDFHBAKJINGGJKFAHAFKFIGINJGFMEHIEOAACPBFIDKMLKCMBPCLONHCKGJGKHBEMOLNCGPAMC","p2pKey":"nVpkO1Xqbojgr4Ks","wakeupServerKey":"e6UBKLIQ4iTD3jbm","wakeupServerList":["47.92.3.201:12306","47.254.35.114:12306","47.91.92.46:12306"]},"p2pId":"TYQJAA-007171-CYEXC,KQNNCV","password":"ad528c03","timeZoneId":"Asia/Calcutta"}

**Comment by 4naveen** [comment]
local_key: d3b960a10611b91e

**Comment by Tuya-DJ** [comment]
your device(6c6ad23b242b9be9e7umcb) is not online

**Comment by 4naveen** [comment]
but it is showing online in app

**Comment by 4naveen** [comment]
all credentials i am getting except initstr and p2pkey for camera device

**Comment by Tuya-DJ** [comment]
please give me  the response of requestWithApiName() again, the pwd is changed  for the deivce (6c17869d9c18886d29tze0)

**Comment by 4naveen** [comment]
ok just a min

**Comment by 4naveen** [comment]
you mean i have to reconfigure the device on cloud once again ?

**Comment by Tuya-DJ** [comment]
now i found your deivce(6c17869d9c18886d29tze0) reseted in 14:12

**Comment by Tuya-DJ** [comment]
![image](https://user-images.githubusercontent.com/46557911/52038685-e2e78f00-256d-11e9-9495-9905d71341a2.png)

**Comment by Tuya-DJ** [comment]
now i can`t test

**Comment by 4naveen** [comment]
D/Tuya: Business api: tuya.m.ipc.config.get {"result":{"password":"ad517d71","timeZoneId":"Asia/Calcutta","skill":"{\"chromecast\":1,\"localStorage\":1,\"sdk_version\":\"3.4.2\",\"echoshow\":1,\"cloudStorage\":1}","p2pConfig":{},"audioAttributes":{"callMode":[1,2],"hardwareCapability":[1,2]},"id":"6c6ad23b242b9be9e7umcb","p2pId":"6EWMNNSSA67V2SET111A"},"t":1548920684833,"success":true,"status":"ok"}

**Comment by 4naveen** [comment]
Why i am not getting initStr and p2pkey ???

**Comment by Tuya-DJ** [comment]
the device p2ptype =1 , it don`t need initStr and p2pkey.

**Comment by 4naveen** [comment]
this method require  those two values
        camera.createDevice(p2pId, mInitStr, mP2pKey, mIsRunSoft);

**Comment by Tuya-DJ** [comment]
you set mInitStr="", mP2pKey=""

**Comment by 4naveen** [comment]
Ok I will try

**Comment by 4naveen** [comment]
I tried but i am getting error
01-31 14:21:33.283 1511-1717/com.test.homesdkdemo E/Tuya: MqttServerManager subscribe: failure[smart/mb/in/6c6ad23b242b9be9e7umcb]

**Comment by 4naveen** [comment]
I tried with new device it is getting added successfully and but againg 
tuya.m.ipc.config.get {"result":{"password":"ad52ccd7","timeZoneId":"Asia/Calcutta","skill":"{\"chromecast\":1,\"localStorage\":1,\"sdk_version\":\"3.4.2\",\"echoshow\":1,\"cloudStorage\":1}","p2pConfig":{},"audioAttributes":{"callMode":[1,2],"hardwareCapability":[1,2]},"id":"6ce54b93fba78e79824y0t","p2pId":"FZGSSANEB69C27Y8111A"},"t":1548930947560,"success":true,"status":"ok"}

**Comment by Tuya-DJ** [comment]
give me localkey for devid(6ce54b93fba78e79824y0t)

**Comment by Tuya-DJ** [comment]
please give me your account (username and password)

**Comment by 4naveen** [comment]
Account: vijayakumar.kabbin@sar-group.com
Password :  sar@123

**Comment by Tuya-DJ** [comment]
the camera is not online now

**Comment by 4naveen** [comment]
Yes now I came out to office so off that camera

**Comment by Tuya-DJ** [comment]
OK，let`s test the camera tomorrow，please make  it  online always

**Comment by Tuya-DJ** [comment]
https://github.com/TuyaInc/tuyasmart_camera_android_sdk

**Comment by Tuya-DJ** [comment]
please see the demo

**Comment by Tuya-DJ** [comment]
change aar: tuyaCamera-3.0.3.aar

**Comment by 4naveen** [comment]
I updated to newer version according to you
but still same issue coming

**Comment by 4naveen** [comment]
### and i am trying to build new demp app as given by wH 
but it is showing build error 


Unable to resolve dependency for ':app@debug/compileClasspath': Could not download rxjava.jar (io.reactivex.rxjava2:rxjava:2.1.7)
Open File
Show Details


Unable to resolve dependency for ':app@debug/compileClasspath': Could not download reactive-streams.jar (org.reactivestreams:reactive-streams:1.0.1)
Open File
Show Details


Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not download rxjava.jar (io.reactivex.rxjava2:rxjava:2.1.7)
Open File
Show Details


Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not download reactive-streams.jar (org.reactivestreams:reactive-streams:1.0.1)
Open File
Show Details


Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not download rxjava.jar (io.reactivex.rxjava2:rxjava:2.1.7)
Open File
Show Details


Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not download reactive-streams.jar (org.reactivestreams:reactive-streams:1.0.1)
Open File
Show Details


Unable to resolve dependency for ':app@release/compileClasspath': Could not download rxjava.jar (io.reactivex.rxjava2:rxjava:2.1.7)
Open File
Show Details


Unable to resolve dependency for ':app@release/compileClasspath': Could not download reactive-streams.jar (org.reactivestreams:reactive-streams:1.0.1)
Open File
Show Details


Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not download rxjava.jar (io.reactivex.rxjava2:rxjava:2.1.7)
Open File
Show Details


Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not download reactive-streams.jar (org.reactivestreams:reactive-streams:1.0.1)
Open File
Show Details

**Comment by 4naveen** [comment]
I have build new  sample app which WH sent 
but still issue is coming

     @Override
        public void onChannelOtherStatus(int errorCode) {

            Log.d(TAG, "onChannelOtherStatus errorCode " + errorCode);
        }

**Comment by 4naveen** [comment]
smart camera

**Comment by 4naveen** [comment]
when i passing p2ptype=1 then i am getting initStr and p2pkey value but video view is not creating and when p2ptype=2 then i am not getting initStr and p2pkey value but then video view is creating

**Comment by Tuya-DJ** [comment]
![1549017390641](https://user-images.githubusercontent.com/46557911/52118088-5a8dea80-2650-11e9-9b66-49f0a06550dc.jpg)

**Comment by Tuya-DJ** [comment]
p2ptype in the deviceBean

**Comment by 4naveen** [comment]
working now
