### ISSUE TITLE
应用切换后台后moniter进程crash：null notification

### ISSUE THREAD

**Issue by MiraclesHed** [TuyaInc/tuyasmart_home_android_sdk#76]
手机：三星G8870
`java.lang.RuntimeException: Unable to start service com.tuya.smart.android.hardware.service.DevTransferService@1261330 with Intent { act=tuya.intent.action.tcp cat=[tuya] cmp=com.dinsafer.fsk.inhouse/com.tuya.smart.android.hardware.service.DevTransferService (has extras) }: java.lang.IllegalArgumentException: null notification
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3931)
        at android.app.ActivityThread.access$1700(ActivityThread.java:240)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1837)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7124)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
     Caused by: java.lang.IllegalArgumentException: null notification
        at android.os.Parcel.createException(Parcel.java:1970)
        at android.os.Parcel.readException(Parcel.java:1934)
        at android.os.Parcel.readException(Parcel.java:1884)
        at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:5053)
        at android.app.Service.startForeground(Service.java:695)
        at com.tuya.smart.android.hardware.service.DevTransferService.onStartCommand(DevTransferService.java:151)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3912)
        at android.app.ActivityThread.access$1700(ActivityThread.java:240) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1837) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7124) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975) 
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.am.ActiveServices.setServiceForegroundInnerLocked(ActiveServices.java:1264)
        at com.android.server.am.ActiveServices.setServiceForegroundLocked(ActiveServices.java:969)
        at com.android.server.am.ActivityManagerService.setServiceForeground(ActivityManagerService.java:25031)
        at android.app.IActivityManager$Stub.onTransact$setServiceForeground$(IActivityManager.java:11377)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:792)`

**Comment by smarxpan** [comment]
将在3.14.0的SDK上修复，请等待更新
