### ISSUE TITLE
android java.lang.NumberFormatException: For input string: "07200091dc4f223f4ddc" 

### ISSUE THREAD

**Issue by MimikFc7** [TuyaInc/tuyasmart_home_android_sdk#81]
Hello, in Android cannot get list sheduller
`TuyaHomeSdk.getTimerManagerInstance().getAllTimerWithDeviceId(this.getDeviceId() , new IGetAllTimerWithDevIdCallback() {`

return exception this.getDeviceId() not a Long, but avery time this is a string
**07200091dc4f223f4ddc**

**Comment by MimikFc7** [comment]
Hello? anybody?

**Comment by blitzfeng** [comment]
> Hello, in Android cannot get list sheduller
> `TuyaHomeSdk.getTimerManagerInstance().getAllTimerWithDeviceId(this.getDeviceId() , new IGetAllTimerWithDevIdCallback() {`
> 
> return exception this.getDeviceId() not a Long, but avery time this is a string
> **07200091dc4f223f4ddc**
> 
> `implementation 'com.tuya.smart:tuyasmart:3.13.0-bata2'`
> 
> full exception:
> `W/System.err: java.lang.NumberFormatException: For input string: "07200091dc4f223f4ddc" W/System.err: at java.lang.Long.parseLong(Long.java:594) W/System.err: at java.lang.Long.valueOf(Long.java:808) W/System.err: at com.tuya.smart.common.o0o0ooooo0.O000000o(TuyaTimerManager.java:366) W/System.err: at com.tuya.smart.common.o0o0ooooo0.getAllTimerWithDeviceId(TuyaTimerManager.java:305) W/System.err: at homealone.ru.models.DeviceModel.getShedullerData(DeviceModel.java:172) W/System.err: at homealone.ru.models.DeviceModel$2.onSuccess(DeviceModel.java:141) W/System.err: at com.tuya.smart.common.o0o0ooooo0$3.O00000Oo(TuyaTimerManager.java:119) W/System.err: at com.tuya.smart.common.o0o0ooooo0$3.onSuccess(TuyaTimerManager.java:111) W/System.err: at com.tuya.smart.android.network.Business$RequestTask$3.run(Business.java:519) W/System.err: at android.os.Handler.handleCallback(Handler.java:873) W/System.err: at android.os.Handler.dispatchMessage(Handler.java:99) W/System.err: at android.os.Looper.loop(Looper.java:216) W/System.err: at android.app.ActivityThread.main(ActivityThread.java:7285) W/System.err: at java.lang.reflect.Method.invoke(Native Method) W/System.err: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) W/System.err: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)`

Hello,the exception is not a problem.We use the method 'Long.parseLong(devId)' to judge the input 'devId' is a device id or a group id.if the exception triggered,it means a device id, otherwise，it's a group id.And we also catch the exception.

**Comment by MimikFc7** [comment]
Hello! But when i call sheduller list after delete app crash and i cant get the sheduller list with this exeption, sometimes that eaxception was ignored, but many time this make a crash

**Comment by MimikFc7** [comment]
you can check this, delete some sheduller list and call sheduller list after. sheduller list will be empty, after reopen app sheduller list will be not ampty

**Comment by blitzfeng** [comment]
> you can check this, delete some sheduller list and call sheduller list after. sheduller list will be empty, after reopen app sheduller list will be not ampty

Ok,I'll check it .Could you upload more crash log?I need the crash info and the context

**Comment by MimikFc7** [comment]
> > you can check this, delete some sheduller list and call sheduller list after. sheduller list will be empty, after reopen app sheduller list will be not ampty
> 
> Ok,I'll check it .Could you upload more crash log?I need the crash info and the context

i can do that, but afer 8 hours.

**Comment by MimikFc7** [comment]
Hello, sorry fro long time answer
` TuyaHomeSdk.getTimerManagerInstance().addTimerWithTask("mytuyaexp", this.device_id, loops, dpssend, time, new IResultStatusCallback() {
            @Override
            public void onSuccess() {
                getShedullerData();
            }

            @Override
            public void onError(String errorCode, String errorMsg) {
                StaticData.BroadcastMessage(ONSHOWERROR,errorMsg);
            }
        });`



`public void getShedullerData()
    {

        TuyaHomeSdk.getTimerManagerInstance().getAllTimerWithDeviceId(this.getDeviceId() , new IGetAllTimerWithDevIdCallback() {
            @Override
            public void onSuccess(ArrayList<TimerTask> taskArrayList)
            {
                shedullerList.clear();

                if( taskArrayList.size() > 0) {
                    for (int i = 0; i < taskArrayList.size(); i++) {

                        if (taskArrayList.get(i).getTimerList() != null) {
                            if (taskArrayList.get(i).getTimerList().size() > 0) {
                                for (Timer value : taskArrayList.get(i).getTimerList()) {
                                    TimerTask owner = taskArrayList.get(i);
                                    TimerTask tm = new TimerTask();
                                    tm.setTimerTaskStatus(owner.getTimerTaskStatus());


                                    ArrayList<Timer> listtm = new ArrayList<>();
                                    listtm.add(value);
                                    tm.setTimerList(listtm);

                                    shedullerList.add(tm);

                                }
                            }
                        }

                    }
                }

                StaticData.BroadcastMessage(SHEDULLERDEVICELOAD,device_id);
            }
            @Override
            public void onError(String errorCode, String errorMsg) {

                StaticData.BroadcastMessage(ONSHOWERROR,errorMsg);
            }
        });
    }`

if create or delete sheduller, items not showing only after reconnect
