### ISSUE TITLE
tuya:monitor service crashes foreground process

### ISSUE THREAD

**Issue by mikep01** [TuyaInc/tuyasmart_home_android_sdk#83]
I'm using the tuya process with a foreground process.  The service launched into the :monitor thread will eventually crash when launched and my process will be killed by android.  This seems to occur on android 8.0 or later, I don't see the same crash on earlier versions.

2020-03-16 21:52:00.309 15903-15903/mpp.tuya4mpp:monitor E/AndroidRuntime: FATAL EXCEPTION: main
    Process: mpp.tuya4mpp:monitor, PID: 15903
    java.lang.RuntimeException: Unable to start service com.tuya.smart.android.hardware.service.DevTransferService@5bec48c with Intent { act=tuya.intent.action.tcp cat=[tuya] cmp=mpp.tuya4mpp/com.tuya.smart.android.hardware.service.DevTransferService (has extras) }: java.lang.IllegalArgumentException: null notification
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3610)
        at android.app.ActivityThread.-wrap20(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6615)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)
     Caused by: java.lang.IllegalArgumentException: null notification
        at android.os.Parcel.readException(Parcel.java:2009)
        at android.os.Parcel.readException(Parcel.java:1951)
        at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:5833)
        at android.app.Service.startForeground(Service.java:699)
        at com.tuya.smart.android.hardware.service.DevTransferService.onStartCommand(DevTransferService.java:151)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3593)
        at android.app.ActivityThread.-wrap20(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6615) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)

**Comment by mikep01** [comment]
If it helps, here's the cause of the crash: "com.tuya.smart.android.hardware.service.DevTransferService.onStartCommand(DevTransferService.java:151)"

It looks like you need a check for the problem in DevTransferService to keep it from crashing (it's trying to startForeground I assume with a null value) and perhaps a better way to start the process.

**Comment by mikep01** [comment]
Might be a duplicate of https://github.com/TuyaInc/tuyasmart_home_android_sdk/issues/76 (I didn't try translating it till now).
Is there a target date for the 3.14.0 release?
